language: java
matrix:
  include:
    - jdk: oraclejdk8
    - jdk: openjdk8
    - jdk: oraclejdk9
    - jdk: openjdk9
    - jdk: openjdk10
    - jdk: openjdk11

script:
  - ./gradlew --version
  - ./gradlew check -i

notifications:
  slack:
    rooms:
      secure: jMQpYpAWpzoOckifq3be/2n02oev6MVvdP/iXRyLM7yEof/VHbai7WjVVFYPk+1k4YjPuYMA87iMuMwYv+BcX2HnY16V9lNvy2fs5hDgJdf2UJFHtMaqs5bbXA/S+5651Cv1hpukRV9P6xXaVsSX1uXcnnqhVW/IFvgson0zfHkm66zsTxzQ/rMP961yKm6fRpzSVe3HyHE7AKPriEcMF/cdQyvHkYP9F98R/vwiDrgjt4uiiVe+CG+sN/VFMpy1lS15A72OiyZ5KRx86m/t76wP/bCTfLkB2utjlLeYJk48xMW5u4w6/lfYWWMUMpDVG4YNUrfhzt8i9UAZ+rOHwSmkMYhUwl6PbQmkbcqPY3zssctdJQma3PPYSDkohnfnraqU+3YrlEndBZFJ7fSMOAdPCXTgyq6nmawiHrF7TO4uF1JTJm36/wwAPO55zA6goKz3iwmVX0V8NVZ7TQOJ8KtEWM1v9jNLBO3aqvN6yWmHTEB4tkr+ObESg4rR9EebmftNWVm9MabXCM7SgnRrjlBDRbc6aAfcUCPOxgrA4GWS32lIe95sC0ZMR/tE//4+YCLF7iWCmconLw0GWl26oxFsWlEf+gGxjMtLm1NLE9Lps6NrJdxc15WKHpmEPQ7lcgKA4YYvEhgq3W4FufriS0TJRu6SUNm8VLXJdGXDUgA=
